# Generated by Django 5.1.7 on 2025-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='team_name',
            field=models.CharField(blank=True, choices=[('Thunder Cats', 'Thunder Cats'), ('Black Mambas 1', 'Black Mambas 1'), ('Forvis Mazars A', 'Forvis Mazars A'), ('Motozone', 'Motozone'), ('Lobatse Cricket Club', 'Lobatse Cricket Club'), ('Pioneers', 'Pioneers'), ('United Gymkhana', 'United Gymkhana'), ('All Stars', 'All Stars'), ('SH Tyre City', 'SH Tyre City'), ('Gujarat Strikers B', 'Gujarat Strikers B'), ('Phoenix', 'Phoenix'), ('Ceylon Cricket Club', 'Ceylon Cricket Club'), ('DJ Devils', 'DJ Devils'), ('BD Cricket Club', 'BD Cricket Club'), ('SKY XI', 'SKY XI'), ('Cubs XI', 'Cubs XI'), ('Nawabz Boys', 'Nawabz Boys'), ('Auto World', 'Auto World'), ('FD Titans', 'FD Titans'), ('Pulse Cricket Stallion', 'Pulse Cricket Stallion'), ('Elite Sports', 'Elite Sports'), ('Excel Strikers', 'Excel Strikers'), ('PWC', 'PWC'), ('Black Mambas 2', 'Black Mambas 2'), ('Moremi Kings (Chennai)', 'Moremi Kings (Chennai)'), ('Forvis Mazars Juniors', 'Forvis Mazars Juniors'), ('Sefalana', 'Sefalana'), ('Friends', 'Friends'), ('A-One', 'A-One'), ('Cheetas', 'Cheetas')], max_length=100),
        ),
    ]
